### ISSUE TITLE
v2.0.5 Issues w/xls Toolkit

### ISSUE THREAD

**Issue by johnellingsworth** [owaspsamm/toolbox-spreadsheet#12]
Interview sheet:

Conditional Formatting:
- Unused rule at F15

Roadmap sheet:

Formulas:

- Secure Build has incorrect formulas for Implementation: Phase 1, 2, 3, 4

- This breaks the roadmap feature
- It also breaks the scorecard calculation

Conditional Formatting:
- J22:J23 is in one record causing errors
- J55:J56 is in one record causing errors
- J130:J132 is in one record causing errors
- J153:J154 is in one record causing errors
- N22:N23 is in one record causing errors
- N55:N56 is in one record causing errors
- N130:N132 is in one record causing errors
- N153:N154 is in one record causing errors
- R22:R23 is in one record causing errors
- R55:R56 is in one record causing errors
- R130:R132 is in one record causing errors
- R153:R154 is in one record causing errors
- V22:V23 is in one record causing errors
- V55:V56 is in one record causing errors
- V130:V132 is in one record causing errors
- V153:V154 is in one record causing errors

- Answer values default to '0' maybe should be blank instead

Roadmap Chart sheet:

Formulas:

- Under Practice Charts, Secure Build, Secure Deployment, and Defect Management practice names are hard coded.

Spider chart:

- Chart does not show color for each phase, only Phase 4

Scorecard:

- Should we change the 'Current' label in each Phase be changed to the Phase name?  The 'Current' column reflects the projected maturity score, and not the initial interview

**Comment by infosecdad** [comment]
Removed the unused conditional formatting rule in Interviews.
Fixed the formulas in Roadmap when fixing for Google Sheets
The reported conditional formatting errors in Roadmap cannot be replicated, seem to test out fine. I wonder if those are actually warnings of a sort, because those are formatting rules that cover two cells with two formatting options, but neither is marked "stop if true"
Fixed the hard coded names in the roadmap chart
The spider chart is showing all colors when tested, the roadmap must have data in it where improvements are made over the phases to see the different colors.
In the scorecard, "Current" was replaced with "Score"

**Comment by maximbaele** [comment]
I believe this ticket can be closed @infosecdad ?
